#!/usr/bin/python -tt
# Project: ac5_applying_naf_framework
# Filename: generate_clab_topology.py
# claudiadeluna
# PyCharm

from __future__ import absolute_import, division, print_function

__author__ = "Claudia de Luna (claudia@indigowire.net)"
__version__ = ": 1.0 $"
__date__ = "5/24/26"
__copyright__ = "Copyright (c) 2023 Claudia"
__license__ = "Python"

"""
generate_clab_topology.py — ContainerLab topology generator for ACL policy testing.

Generates a complete, ready-to-deploy ContainerLab file tree under
output/containerlab_topology/ by combining two sources of truth:

  1. Lab topology structure (node kinds, images, VLAN numbering, link wiring)
     Reference implementation: https://github.com/cldeluna/internet-cisco-iol-l2-clab
     The topology uses a Cisco IOL L2 switch connected to an Alpine Linux server
     container (running dnsmasq + nginx) and an Alpine Linux client container.

  2. IP address policy (DHCP server IP, DNS server IP, ip helper-address values)
     Source: acl_aerleon/def/dhcp.yaml and acl_aerleon/def/dns.yaml
     Auto-discovered at ../acl_aerleon/def/ relative to this script.
     Re-run this script after any Step 1 SoT commit to refresh the topology.

Only the FIRST DHCP server entry from dhcp.yaml is used.  The test validates
that the ACL permits DHCP relay traffic to that server IP — not DHCP server
redundancy.  The server container is assigned that IP on eth1; the switch SVIs
carry ip helper-address pointing to it; dnsmasq serves DHCP ranges for the
three client VLANs (10/20/30) using RFC5737 documentation ranges.

Output files (all stamped with a created: timestamp in their headers):
  internet-cisco-iol-l3-lab.clab.yml
  sw1.partial.cfg
  server/dnsmasq.conf
  server/start.sh
  server/nginx-default.conf
  client/start.sh

Usage:
  uv run generate_clab_topology.py
  uv run generate_clab_topology.py --sot-dir PATH --output-dir PATH
"""

import argparse
import datetime
import ipaddress
import os
import stat
import yaml
import jinja2


# ---------------------------------------------------------------------------
# Inline Jinja2 templates — one per output file
# All IP values are injected from acl_aerleon/def/ at render time.
# ---------------------------------------------------------------------------

_TOPOLOGY_TMPL = """\
# Generated by generate_clab_topology.py
# created:      {{ created_ts }}
# DHCP server:  {{ dhcp_server_ip }} ({{ dhcp_comment }})
# DNS  server:  {{ dns_server_ip }} ({{ dns_comment }})
# Re-run this script after any change to acl_aerleon/def/ to refresh these files.

name: internet-cisco-iol-l2-lab

topology:
  nodes:
    core-sw1:
      kind: cisco_iol
      image: vrnetlab/cisco_iol:L2-17.15.01
      type: L2
      startup-config: sw1.partial.cfg
      ports:
        - "20512:22"
        - "2223:23"

    server:
      kind: linux
      image: alpine:3.19
      binds:
        - server/dnsmasq.conf:/etc/dnsmasq.conf
        - server/nginx-default.conf:/etc/nginx/http.d/default.conf
        - server/start.sh:/start.sh
      exec:
        - sh /start.sh

    client:
      kind: linux
      image: alpine:3.19
      binds:
        - client/start.sh:/start.sh
      ports:
        - "20513:22"
      exec:
        - sh /start.sh

  links:
    # Client — one port per client VLAN
    - endpoints: ["client:eth1", "core-sw1:Ethernet0/1"]
    - endpoints: ["client:eth2", "core-sw1:Ethernet0/2"]
    - endpoints: ["client:eth3", "core-sw1:Ethernet0/3"]
    # Server — single access link on VLAN {{ server_vlan }}
    - endpoints: ["server:eth1", "core-sw1:Ethernet1/0"]
"""

_SW_CONFIG_TMPL = """\
!
! Cisco IOL Switch — partial startup config
! Generated by generate_clab_topology.py from acl_aerleon/def/
! created     : {{ created_ts }}
! DHCP server : {{ dhcp_server_ip }} ({{ dhcp_comment }})
! DNS  server : {{ dns_server_ip }} ({{ dns_comment }})
!
vlan {{ server_vlan }}
 name SERVER_VLAN
{% for v in client_vlans %}
vlan {{ v.id }}
 name {{ v.name }}
{% endfor %}
!
! Server SVI — routed to the DHCP/DNS server container
interface Vlan{{ server_vlan }}
 description server-vlan data
 ip address {{ server_svi_ip }} {{ server_subnet_mask }}
 no shutdown
!
{% for v in client_vlans %}
! Client VLAN {{ v.id }} — ip helper relays DHCP to {{ dhcp_server_ip }}
interface Vlan{{ v.id }}
 description {{ v.name | lower }} data
 ip address {{ v.svi_ip }} {{ v.mask }}
 ip helper-address {{ dhcp_server_ip }}
 no shutdown
!
{% endfor %}
! Trunk ports toward client container
interface Ethernet0/1
 switchport mode trunk
 no shutdown
!
interface Ethernet0/2
 switchport mode trunk
 no shutdown
!
interface Ethernet0/3
 switchport mode trunk
 no shutdown
!
! Access port toward server container
interface Ethernet1/0
 switchport access vlan {{ server_vlan }}
 switchport mode access
 no shutdown
!
ip routing
!
end
"""

_DNSMASQ_TMPL = """\
# Generated by generate_clab_topology.py from acl_aerleon/def/
# created        : {{ created_ts }}
# DHCP server IP : {{ dhcp_server_ip }}
# DNS  server IP : {{ dns_server_ip }}

interface=eth1
bind-interfaces

{% for v in client_vlans %}
dhcp-range=set:vlan{{ v.id }},{{ v.dhcp_start }},{{ v.dhcp_end }},{{ v.mask }},12h
dhcp-option=tag:vlan{{ v.id }},option:router,{{ v.svi_ip }}
dhcp-option=tag:vlan{{ v.id }},option:dns-server,{{ dns_server_ip }}
{% endfor %}
"""

_SERVER_START_TMPL = """\
#!/bin/sh
# Generated by generate_clab_topology.py from acl_aerleon/def/
# created  : {{ created_ts }}
# Assigns the first DHCP server IP from dhcp.yaml to eth1.

ip addr add {{ dhcp_server_ip }}/{{ server_prefix_len }} dev eth1
ip link set eth1 up

apk add --no-cache dnsmasq nginx > /dev/null 2>&1

nginx
dnsmasq --no-daemon --log-queries
"""

_CLIENT_START_TMPL = """\
#!/bin/sh
# Generated by generate_clab_topology.py
# created  : {{ created_ts }}
{% for v in client_vlans %}
ip link set eth{{ loop.index }} up
{% endfor %}
sleep 2
"""

_NGINX_TMPL = """\
# Generated by generate_clab_topology.py
# created  : {{ created_ts }}
server {
    listen 80 default_server;
    root /var/www/localhost/htdocs;
    index index.html;
}
"""

# Map relative output path → template string
_FILE_TEMPLATES = {
    "internet-cisco-iol-l3-lab.clab.yml": _TOPOLOGY_TMPL,
    "sw1.partial.cfg": _SW_CONFIG_TMPL,
    os.path.join("server", "dnsmasq.conf"): _DNSMASQ_TMPL,
    os.path.join("server", "start.sh"): _SERVER_START_TMPL,
    os.path.join("server", "nginx-default.conf"): _NGINX_TMPL,
    os.path.join("client", "start.sh"): _CLIENT_START_TMPL,
}


def load_sot(sot_dir: str) -> dict:
    """Read dhcp.yaml and dns.yaml and return the FIRST server IP of each type.

    Only the first DHCP server entry is used — we are testing ACL behaviour,
    not DHCP server redundancy.

    Args:
        sot_dir: Absolute path to acl_aerleon/def/.

    Returns:
        Dict with dhcp_server_ip, dhcp_comment, dns_server_ip, dns_comment.
    """
    for fname in ("dhcp.yaml", "dns.yaml"):
        path = os.path.join(sot_dir, fname)
        if not os.path.isfile(path):
            raise FileNotFoundError(f"SoT file not found: {path}")

    with open(os.path.join(sot_dir, "dhcp.yaml")) as fh:
        dhcp = yaml.safe_load(fh)
    with open(os.path.join(sot_dir, "dns.yaml")) as fh:
        dns = yaml.safe_load(fh)

    dhcp_entry = dhcp["networks"]["DHCP_SERVERS"]["values"][0]
    dns_entry = dns["networks"]["DNS_SERVERS"]["values"][0]

    return {
        "dhcp_server_ip": dhcp_entry["address"].split("/")[0],
        "dhcp_comment": dhcp_entry.get("comment", "DHCP Server"),
        "dns_server_ip": dns_entry["address"].split("/")[0],
        "dns_comment": dns_entry.get("comment", "DNS Server"),
    }


def build_context(sot: dict) -> dict:
    """Build the full Jinja2 rendering context.

    Client VLANs use RFC5737 documentation ranges — they are lab infrastructure,
    not policy values, so they are kept static.  Only the server IPs are sourced
    from the SoT YAML files.

    Args:
        sot: Dict returned by load_sot().

    Returns:
        Context dict consumed by all templates.
    """
    dhcp_ip = sot["dhcp_server_ip"]
    network = ipaddress.ip_interface(f"{dhcp_ip}/24").network
    server_svi_ip = str(list(network.hosts())[0])

    client_vlans = [
        {"id": 10, "name": "CLIENT_VLAN_10", "svi_ip": "192.0.2.1",
         "mask": "255.255.255.0", "dhcp_start": "192.0.2.100", "dhcp_end": "192.0.2.200"},
        {"id": 20, "name": "CLIENT_VLAN_20", "svi_ip": "198.51.100.1",
         "mask": "255.255.255.0", "dhcp_start": "198.51.100.100", "dhcp_end": "198.51.100.200"},
        {"id": 30, "name": "CLIENT_VLAN_30", "svi_ip": "203.0.113.1",
         "mask": "255.255.255.0", "dhcp_start": "203.0.113.100", "dhcp_end": "203.0.113.200"},
    ]

    return {
        "dhcp_server_ip": dhcp_ip,
        "dhcp_comment": sot["dhcp_comment"],
        "dns_server_ip": sot["dns_server_ip"],
        "dns_comment": sot["dns_comment"],
        "server_vlan": 100,
        "server_svi_ip": server_svi_ip,
        "server_subnet_mask": str(network.netmask),
        "server_prefix_len": network.prefixlen,
        "client_vlans": client_vlans,
        "created_ts": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    }


def render_files(output_dir: str, context: dict) -> list:
    """Render all templates and write the containerlab topology file tree.

    Args:
        output_dir: Root of the output/containerlab_topology/ directory.
        context: Rendering context from build_context().

    Returns:
        List of absolute paths for every written file.
    """
    env = jinja2.Environment(
        loader=jinja2.BaseLoader(),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    written = []
    for rel_path, tmpl_str in _FILE_TEMPLATES.items():
        full_path = os.path.join(output_dir, rel_path)
        parent = os.path.dirname(full_path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        content = env.from_string(tmpl_str).render(**context)
        with open(full_path, "w") as fh:
            fh.write(content)
        if rel_path.endswith(".sh"):
            os.chmod(full_path, os.stat(full_path).st_mode | stat.S_IXUSR | stat.S_IXGRP)
        written.append(full_path)
        print(f"  wrote  {full_path}")
    return written


def main():
    parser = argparse.ArgumentParser(
        description="Generate ContainerLab topology files from acl_aerleon/def/ source of truth",
        epilog="Usage: python generate_clab_topology.py [--sot-dir PATH] [--output-dir PATH]",
    )
    parser.add_argument(
        "--sot-dir",
        default=None,
        help="Path to acl_aerleon/def/ (default: auto-discovered relative to this script)",
    )
    parser.add_argument(
        "--output-dir",
        default=None,
        help="Destination directory (default: output/containerlab_topology/ next to this script)",
    )
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))

    sot_dir = args.sot_dir or os.path.join(script_dir, "..", "acl_aerleon", "def")
    sot_dir = os.path.abspath(sot_dir)

    output_dir = args.output_dir or os.path.join(script_dir, "output", "containerlab_topology")
    output_dir = os.path.abspath(output_dir)

    print(f"\nSource of Truth : {sot_dir}")
    print(f"Output directory: {output_dir}\n")

    sot = load_sot(sot_dir)
    print(f"  DHCP server (1st entry): {sot['dhcp_server_ip']}  — {sot['dhcp_comment']}")
    print(f"  DNS  server (1st entry): {sot['dns_server_ip']}  — {sot['dns_comment']}\n")

    context = build_context(sot)
    written = render_files(output_dir, context)

    print(f"\n{len(written)} files written.")
    print(f"Deploy: cd {output_dir} && sudo clab deploy -t internet-cisco-iol-l3-lab.clab.yml\n")


# Standard call to the main() function.
if __name__ == '__main__':

    parser = argparse.ArgumentParser(
        description="Generate ContainerLab topology files from SoT YAML",
        epilog="Usage: python generate_clab_topology.py",
    )
    arguments = parser.parse_args()
    main()
