[project]
name = "ac5-applying-naf-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.3",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "netmiko>=4.7.0",
    "prefect>=3.7.4",
    "python-dotenv>=1.0.0",
    "requests>=2.34.2",
    "uvicorn>=0.49.0",
]

[tool.uv.workspace]
members = [
    "aerleon",
    "acl_aerleon",
]
